language: generic
sudo: required
cache:
  timeout: 600
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
services:
  - docker
jobs:
  include:
    - stage: Build & Test
      script:
        - docker pull cita/cita-build:latest
        - bash 'scripts/ci.sh'
before_cache:
    - sudo chown -R travis:travis $HOME/.cargo
    - sudo chown -R travis:travis $TRAVIS_BUILD_DIR/target
