[workspace]
members = ["cita-auth"
,"cita-jsonrpc"
,"cita-chain"
,"cita-tendermint"
,"cita-network"
,"cita-executor"
,"cita-forever"
,"tools/create_key_addr"
,"tests/trans_evm"
,"tests/chain_performance"
,"tests/amqp"
,"tests/latency"
,"tests/jsonrpc_performance"
,"tests/benchmark_ws"
,"tests/chain_performance_by_mq"
,"tests/benchmark_execute_transaction"
]

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = 'unwind'
