version: 2
jobs:
  build:
    docker:
      - image: cita/cita-build:latest
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - checkout
      - run:
          name: checkout_submodule
          command: 'git submodule update --init'
      - run:
          name: format
          command: 'cargo fmt --all  -- --write-mode diff'
      - run:
          name: build
          command: 'RUSTFLAGS="-F warnings" cargo build --all'
          no_output_timeout: 20m
      - run:
          name: check_cargolock
          command: '[ $(git status --short Cargo.lock | wc -l) -ne 0 ] && echo "[Error] Please update Cargo.lock BEFORE commit." && git diff Cargo.lock && exit 1 || true'
      - save_cache:
          key: cita-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/cita-build
      - save_cache:
          key: deps-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo

  basic_test:
    docker:
      - image: cita/cita-build:latest
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - restore_cache:
          key: cita-build-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: deps-{{ checksum "Cargo.lock" }}
      - run:
          name: test
          command: 'RUSTFLAGS="-F warnings" cargo test --tests'

  basic_test_coverage:
    docker:
      - image: cita/cita-build:latest
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - restore_cache:
          key: cita-build-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: deps-{{ checksum "Cargo.lock" }}
      - run:
          name: test-coverage
          command: |
            bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
            cargo tarpaulin \
              --packages cita-auth \
              --packages cita-jsonrpc \
              --packages cita-chain \
              --packages core \
              --packages common-types \
              --packages cita-tendermint \
              --packages cita-network \
              --packages cita-executor \
              --packages core-executor \
              --packages cita-forever \
              --packages jsonrpc_types \
              --skip-clean --coveralls ${COVERALLS_TOKEN}

  integrate_test:
    docker:
      - image: cita/cita-build:latest
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - restore_cache:
          key: cita-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: config
          command: './scripts/release.sh debug'
      - run:
          name: basic
          command: './tests/integrate_test/cita_basic.sh'
      - run:
          name: byzantine
          command: './tests/integrate_test/cita_byzantinetest.sh'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - basic_test:
          requires:
            - build
      - basic_test_coverage:
          requires:
            - build
      - integrate_test:
          requires:
            - build
